### ISSUE TITLE
运行在mirai上错误

### ISSUE THREAD

**Issue by wqy0916** [Hellobaka/LoliconApiSetuBot#2]
![image](https://user-images.githubusercontent.com/38550132/99518357-5c8d7e80-2988-11eb-8eb8-652281d54925.png)
关键词搜图的时候会错误 请问这是什么问题呢

**Comment by Hellobaka** [comment]
由于本插件使用的搜图来源加上了授权限制，请按以下步骤获取Auth码，填入配置即可：

0. 从release下载新插件版本
1. 访问`https://pixivic.com/`注册一个账号
2. 按F12打开网页控制台，并将页面切换至`网络/Network`页
3. 在镜像站搜索任意关键字
4. 查看F12捕获到的请求，添加过滤条件`illustrations`，点击并在右侧寻找authorization字段，复制字段内全部内容
![image](https://user-images.githubusercontent.com/50934714/99892376-485ebf80-2caf-11eb-8914-4c0bbb817b69.png)
5. 打开插件配置文件(Config.ini)，在[Config]下，添加新的一行`PixivicAuth=`，之后将复制的auth码复制进去，重载插件即可正常搜图
![image](https://user-images.githubusercontent.com/50934714/99892419-a8edfc80-2caf-11eb-95e2-b3e4b38b317a.png)
ps：这个授权码也不清楚多长时间刷新一次，失效了就去重新拉一份

**Comment by wqy0916** [comment]
谢谢

**Comment by wqy0916** [comment]
用#搜图+关键字就会提示错误
![image](https://user-images.githubusercontent.com/38550132/99975235-e5962280-2d99-11eb-9814-c09a6815cdd7.png)
2020-11-23 22:34:15 I/MiraiNative: [水银涩图机 搜索详情] 图片下载失败，错误信息:在 WebClient 请求期间发生异常。
2020-11-23 22:34:15 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessage(GroupImpl.kt:293)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:155)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
#setu命令和其他的命令都正常下载图片
![image](https://user-images.githubusercontent.com/38550132/99975332-ff376a00-2d99-11eb-885d-b7375e12a138.png)

**Comment by Hellobaka** [comment]
如果不是每次必发生，那有可能是这张图片被删掉了，我刚才尝试了拉取这个关键字的图片两三次，都是可以的

**Comment by wqy0916** [comment]
好的 我试试 太麻烦你了

**Comment by Hellobaka** [comment]
有问题可以直接加群来问：671467200
